name: "Hello World Workflow"

on: 
    push:
        branches:
            - main
            - production


jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: "Print Hello World"
              run: echo "Hello, World!"
            
            - name: "Print Date"
              run: date


