name: "Multievent Workflow"
on:
    push:
        branches:
            - test

    pull_request:
        branches:
            - main


jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Runs on push on test branch"
              run: echo "Push on Test branch."

    on-pr:
        if: github.event_name == 'pull_request'
        runs-on: ubunu-latest
        steps:
            - name: "Runs of PR to main branch"
              run: echo "Pull Request to Main branch."


