name: "Multievent Workflow"
on:
    push:
        branches:
            - test




jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Runs on push on test branch"
              run: "Push on Test branch."


