name: "Multievent Workflow"

on:
    push:
        branches:
            - main
            - test

    pull_request:
        branches:
            - main
        types:
            - opened
            - closed

    workflow_dispatch:

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Runs on push on test branch"
              run: echo "Push on Test branch."

    on-pr:
        if: github.event_name == 'pull_request'
        runs-on: ubunu-latest
        steps:
            - name: "Runs of PR to main branch"
              run: echo "Pull Request to Main branch."

    on-workflow-dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Runs on workflow dispatch"
              run: echo "Workflow dispatched manually."

    on-pr-opened:
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
            - name: "Runs on PR opened"
              run: echo "Pull Request Opened."

    on-pr-closed:
        if: github.event_name == 'pill_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Runs on PR closed"
              run: echo "Pull Request Closed."


